version: '3.8'

services:
  template-backend:
    build: ./template-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  template-frontend:
    build: ./template-frontend
    ports:
      - "4000:4000"
    depends_on:
      - template-backend

  postgres:
    container_name: postgres_container
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres-data:
