version: '3.8'

services:
  backend:

    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend

  mongo:
    image: mongo:4.2
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
